### ISSUE TITLE
The public AngleBetween(Vector3 a, Vector3 b) returns a NaN

### ISSUE THREAD

**Issue by tool-buddy** [lordofduct/spacepuppy-unity-framework#6] opened 2017-09-16 15:49 UTC
Yo will get a NaN if you compute the angle between these two vectors
       var v1 = new Vector3(-0.6986121f, -3.21898442E-05f, 0.7155002f);
and
       var v2 = new Vector3(-0.6986134f, 1.31183053E-09f, 0.7154993f);

**Comment by lordofduct** [comment] 2017-09-16 20:23
Resolving - the issue is that the dot product of these 2 vectors divided by their magnitudes, results in a float with small amount of float error putting them ever so slightly over 1. Which Mathf.Acos returns NaN for.

Resolved by constraining the values to be from -1 to 1. Like so:
        public static float AngleBetween(Vector3 a, Vector3 b)
        {
            // // Due to float error the dot / mag can sometimes be ever so slightly over 1, which can cause NaN in acos.
            //return Mathf.Acos(Vector3.Dot(a, b) / (a.magnitude * b.magnitude)) * MathUtil.RAD_TO_DEG;
            double d = (double)Vector3.Dot(a, b) / ((double)a.magnitude * (double)b.magnitude);
            if (d >= 1d) return 0f;
            else if (d <= -1d) return 180f;
            return (float)System.Math.Acos(d) * MathUtil.RAD_TO_DEG;
        }

Will upload changes with next changeset.

**Closed as completed** 2017-09-16 20:23 UTC
